package com.cyberark.authenticator;

import org.springframework.http.ResponseEntity;
import org.springframework.http.converter.json.MappingJackson2HttpMessageConverter;
import org.springframework.web.client.RestTemplate;

import java.io.IOException;
import java.util.Collections;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App
{
    public static void main(String[] args)
    {
        System.out.println("Authenticator starting");
        int port = 18923;

        BasicServer srv;
        try
        {
            IInvestigator inv = new Investigator();
            srv = new InvestigatorServer(port,inv);
            System.out.println("Server Initialized");
            srv.run();
        }
        catch (IOException e)
        {
            System.err.println("Failed to start server");
            e.printStackTrace();
        }

        System.exit(0);
    }
}
